### ISSUE TITLE
1.1.11 failed to start

### ISSUE THREAD

**Issue by vsatmydynipnet** [xbrowsersync/api#39]
I tried to upgrade from 1.1.9 to 1.1.11 but results in following error after update:

{"name":"xBrowserSync_api","hostname":"syncme.mydomain.tld","pid":721,"level":50,"req":null,"err":{"message":"Cannot read property 'length' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'length' of undefined\n    at pathtoRegexp (/usr/home/xbrowsersync/API/node_modules/path-to-regexp/index.js:63:49)\n    at new Layer (/usr/home/xbrowsersync/API/node_modules/express/lib/router/layer.js:45:17)\n    at Function.use (/usr/home/xbrowsersync/API/node_modules/express/lib/router/index.js:464:17)\n    at Function.<anonymous> (/usr/home/xbrowsersync/API/node_modules/express/lib/application.js:220:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (/usr/home/xbrowsersync/API/node_modules/express/lib/application.js:217:7)\n    at Server.prepareRoutes (/usr/home/xbrowsersync/API/dist/core/server.js:312:18)\n    at Server.<anonymous> (/usr/home/xbrowsersync/API/dist/core/server.js:76:22)\n    at Generator.next (<anonymous>)\n    at /usr/home/xbrowsersync/API/dist/core/server.js:14:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/home/xbrowsersync/API/dist/core/server.js:10:12)\n    at Server.init (/usr/home/xbrowsersync/API/dist/core/server.js:72:16)\n    at Object.<anonymous> (/usr/home/xbrowsersync/API/dist/api.js:6:8)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)"},"msg":"Service failed to start","time":"2020-02-24T09:29:40.290Z","v":0}

**Comment by vsatmydynipnet** [comment]
Sorry, I close that again, but for reference i have overseen:

diff -u settings.default.json.1.1.9 settings.default.json.1.1.11 
--- settings.default.json.1.1.9	2019-06-24 10:50:46.879551000 +0200
+++ settings.default.json.1.1.11	2020-01-18 06:06:27.000000000 +0100
@@ -6,7 +6,7 @@
     "connTimeout": 30000,
     "host": "127.0.0.1",
     "name": "xbrowsersync",
-    "useSRV" : false,
+    "useSRV": false,
     "username": "",
     "password": "",
     "port": 27017
@@ -34,7 +34,8 @@
       "enabled": false,
       "keyPath": ""
     },
-    "port": 8080
+    "port": 8080,
+    "relativePath": "/"
   },
   "status": {
     "allowNewSyncs": true,
@@ -49,4 +50,4 @@
     "maxRequests": 1000,
     "timeWindow": 300000
   }
-}
+}
\ No newline at end of file
