### ISSUE TITLE
mobile app does not work but windows chrome does

### ISSUE THREAD

**Issue by SimonMcN** [xBrowserSync/API#84]
I have a docker container reverse proxied by nginx proxy manager on port 8080. but using nginx SSL
I'm using split dns but both hosts are connecting to the same place.

eg: xbrowsersync.atmyhome.com

But I'm confused that the desktop is working but the phone doesn't.  The SSL certs are letsencrypt valid and it all works on the desktop

**Comment by SimonMcN** [comment]
```2022-10-29 15:34:59.853	[trace]	Installed v1.5.2
2022-10-29 15:34:59.873	[trace]	Starting up
2022-10-29 15:34:59.985	[trace]	{"displayHelp":true,"checkForAppUpdates":true,"appVersion":"1.5.2","platform":{"name":"Android","device":"samsung SM-G965F"}}
2022-10-29 15:35:14.973	[trace]	Scanned: fe5dd08be9c945e58ba89bca8bd92a3d|$$|https://xbrowsersync.home.bob.co.uk
2022-10-29 15:35:16.035	[trace]	Service url changed to: https://xbrowsersync.home.bob.co.uk
2022-10-29 15:35:16.323	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:35:16.541	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:36:40.885	[trace]	Scanned: fe5dd08be9c945e58ba89bca8bd92a3d|$$|https://xbrowsersync.home.bob.co.uk
2022-10-29 15:36:41.906	[trace]	Service url changed to: https://xbrowsersync.home.bob.co.uk
2022-10-29 15:36:42.062	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:36:42.211	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:36:50.532	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:36:53.510	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:36:58.667	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:37:15.430	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:37:33.755	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:38:33.764	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:38:37.175	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:38:41.818	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:38:52.081	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:41:02.976	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:41:26.801	[trace]	Scanned: fe5dd08be9c945e58ba89bca8bd92a3d|$$|https://xbrowsersync.home.bob.co.uk
2022-10-29 15:41:27.835	[trace]	Service url changed to: https://xbrowsersync.home.bob.co.uk
2022-10-29 15:41:27.999	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:41:28.105	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:44:05.776	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:44:07.504	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:48:00.644	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-10-29 15:50:03.453	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)```

**Comment by SimonMcN** [comment]
Maybe I spoke too soon.  Chrome error log

`2022-10-29 13:10:42.630	[trace]	Installed v1.5.2
2022-10-29 13:10:42.633	[trace]	Starting up
2022-10-29 13:10:42.646	[trace]	{"checkForAppUpdates":true,"displayHelp":true,"displayPermissions":true,"syncBookmarksToolbar":true,"appVersion":"1.5.2","platform":{"name":"chrome","version":"106.0.0","mobile":false,"os":"Windows 10"}}
2022-10-29 13:11:03.189	[trace]	Optional permissions granted
2022-10-29 15:30:43.667	[trace]	Service url changed to: https://xbrowsersync.home.bob.co.uk
2022-10-29 15:31:52.956	[trace]	Sync eshog2 (push) queued
2022-10-29 15:31:52.957	[trace]	Processing sync eshog2 (0 in queue)
2022-10-29 15:31:53.222	[trace]	Sync enabled
2022-10-29 15:31:53.340	[trace]	Remote bookmarks data updated at 2022-10-29T15:31:52.608Z
2022-10-29 15:31:53.345	[trace]	New sync id created: fe5dd08be9c945e58ba89bca8bd92a3d
2022-10-29 15:48:28.001	[trace]	Reverting data to installation state from 2022-10-29T13:10:42.622Z
2022-10-29 15:48:28.022	[trace]	Sync 1h8rlu0 (pull) queued
2022-10-29 15:48:28.025	[trace]	Processing sync 1h8rlu0 (0 in queue)
2022-10-29 15:48:30.102	[trace]	Local population completed in 1.995s
2022-10-29 15:49:33.743	[trace]	Sync lb6lso (pull) queued
2022-10-29 15:49:33.745	[trace]	Processing sync lb6lso (0 in queue)
2022-10-29 15:49:34.517	[trace]	Local population completed in 0.66s
2022-10-29 15:49:34.522	[trace]	Sync enabled
2022-10-29 15:49:34.526	[trace]	Synced to existing id: fe5dd08be9c945e58ba89bca8bd92a3d
2022-10-29 16:04:34.599	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2389:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:125)
2022-10-29 16:04:34.601	[trace]	Could not check for updates, no connection
2022-10-30 08:18:32.172	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2389:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at y.onabort (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:301) at N (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:146) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:113:58 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15)
2022-10-30 08:18:32.175	[trace]	Could not check for updates, no connection
2022-10-30 08:19:14.526	[trace]	onCreated event detected
2022-10-30 08:19:15.546	[trace]	Sync ezmbv8 (push) queued
2022-10-30 08:19:15.638	[trace]	Sync ezmbv8 failed
2022-10-30 08:19:15.645	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2022-10-30 08:19:15.661	[trace]	Sync 1u03h0x (pull) queued
2022-10-30 08:19:15.668	[trace]	Processing sync 1u03h0x (0 in queue)
2022-10-30 08:19:16.512	[trace]	Local population completed in 0.642s
2022-10-30 08:19:16.516	[trace]	Local sync data refreshed
2022-10-31 09:26:49.872	[trace]	Starting up
2022-10-31 09:26:49.925	[trace]	{"checkForAppUpdates":true,"displayHelp":false,"displayOtherSyncsWarning":false,"displayPermissions":false,"lastUpdated":"2022-10-29T15:31:52.608Z","serviceUrl":"https://xbrowsersync.home.bob.co.uk","syncBookmarksToolbar":true,"syncEnabled":true,"syncId":"fe5dd08be9c945e58ba89bca8bd92a3d","syncVersion":"1.5.2","appVersion":"1.5.2","platform":{"name":"chrome","version":"106.0.0","mobile":false,"os":"Windows 10"}}
2022-10-31 09:27:00.968	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2389:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at y.onabort (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:301) at N (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:146) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:113:58 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15)
2022-10-31 09:27:00.970	[trace]	Connection to API failed, retrying check for sync updates momentarily
2022-10-31 09:27:04.941	[trace]	Couldn’t check for new version`
